### ISSUE TITLE
Help understanding how this library is designed?

### ISSUE THREAD

**Issue by WildYorkies** [FCO/Test-Fuzz#3]
1. The library exposes the `is fuzzed` trait, which is defined in `Test::Fuzz` module.

2. `is fuzzed` takes a routine and adds the `Test::Fuzz::Fuzzed` role onto it.

3. `Test::Fuzz::Fuzzed` role uses `Test::Fuzz::AggGenerators` role as a mixin to build the test cases (it's possible to mixin a role with another role?)

4. `Test::Fuzz::AggGenerators` role uses `Test::Fuzz::Generator` as a mixin to build up an array of test generators for each routine

5. `Test::Fuzz::Generators` is where you define what each type's tests should look like. This is used in the top level `Test::Fuzz`. If you design new tests for different types, they will go in here. (not clear how it's used in Test::Fuzz though)

**Comment by FCO** [comment]
Test::fuzz uses a method "generate-samples" of the type being tested to get the samples. Int and Str doesn't have that method, so generators package include that method into Int and Str (and should do that to other types too). So, when I use Test::Fuzz I load Test::Fuzz::Generatos to augment the Int and Str to let me get samples.

I'm not sure if I understood your question...

**Comment by FCO** [comment]
Yes, it is possible to mixin a role with another role...

**Comment by WildYorkies** [comment]
Just wanted to wrap my head around the library. That actually helps, yes. 

Are you looking to add other types to `Test::Fuzz::Generators`? Need help with that?

**Comment by FCO** [comment]
Yes! I do need help with that! :)
